services:
  postgres:
    # PostgreSQL + pgvector extension
    image: postgres:15-alpine
    container_name: strava-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DB_PORT-5432}:5432

  strava-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: strava-backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      RUN_MAIN: true  # comment if want to avoid running scheduler
    command: >
      bash -c "
      python backend/manage.py migrate;
      python backend/manage.py migrate api;
      python backend/manage.py runserver_plus --cert-file cert.pem --key-file key.pem 0.0.0.0:8000;
      "
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./backend:/backend
      - ./cert.pem:/cert.pem
      - ./key.pem:/key.pem

  test-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: strava-test-backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    command: >
      sh -c "coverage run --source='.' manage.py test api --force-color &&
             coverage report --fail-under=65"

volumes:
  postgres_data:
