services:
  postgres:
    # PostgreSQL + pgvector extension
    image: postgres:15-alpine
    container_name: strava-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT-5432}:5432

volumes:
  postgres_data:
