services:
  postgres:
    # PostgreSQL + pgvector extension
    image: postgres:15-alpine
    container_name: strava-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT-5432}:5432

  test-backend:
    build:
      context: ./strava_zones_backend
      dockerfile: Dockerfile.dev
    container_name: strava-test-backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    command: >
      sh -c "coverage run --source='.' manage.py test api --force-color &&
             coverage report --fail-under=65"

volumes:
  postgres_data:
